# Generated by Django 6.0 on 2026-03-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_product_low_stock_threshold_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Negative = stock out, Positive = stock in')),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('return', 'Return')], default='sale', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Order number or note', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
